'use strict';

import { ApiPropertyOptional } from '@nestjs/swagger';

import { AbstractDto } from '../common/dto/AbstractDto';
import { UserEntity } from '../entities/user.entity';
import { UtilsService } from '../providers/utils.service';

export class UserDto extends AbstractDto {

    @ApiPropertyOptional()
    email: string;

    @ApiPropertyOptional()
    onboarded: boolean;

    @ApiPropertyOptional()
    isAutoGenerated?: boolean;

    verificationToken?: string;

    constructor(user: UserEntity) {
        super(user);
        this.email = user.email;
        this.onboarded = user.onboarded;
        this.isAutoGenerated = user.isAutoGenerated;
        this.verificationToken = user.verificationToken;
    }
}
