import { Column, Entity } from 'typeorm';

import { AbstractEntity } from '../common/abstract.entity';
import { RoleType } from '../common/constants/role-type';
import { UserDto } from '../dto/UserDto';

@Entity({ name: 'user' })
export class UserEntity extends AbstractEntity<UserDto> {
    @Column({ type: 'enum', enum: RoleType, default: RoleType.USER })
    role: RoleType;

    @Column({ unique: true, nullable: true })
    email: string;

    @Column({ nullable: true })
    password: string;

    @Column({ nullable: false, default: false })
    isVerified: boolean;

    @Column({ nullable: false, default: false })
    onboarded: boolean;

    @Column({ default: false, nullable: true })
    isAutoGenerated?: boolean;

    @Column({ nullable: true })
    expoPushToken: string;

    // TODO: remove
    verificationToken?: string;

    dtoClass = UserDto;
}
